/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingId = IDL.Nat;
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const FieldId = IDL.Nat;
export const BookingView = IDL.Record({
  'id' : BookingId,
  'status' : BookingStatus,
  'teamName' : IDL.Text,
  'userId' : UserId,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'time' : IDL.Text,
  'playerCount' : IDL.Nat,
  'priceDt' : IDL.Float64,
  'durationMinutes' : IDL.Nat,
  'paymentReference' : IDL.Opt(IDL.Text),
  'fieldId' : FieldId,
});
export const PaymentResult = IDL.Variant({
  'ok' : BookingView,
  'err' : IDL.Text,
});
export const CreateBookingInput = IDL.Record({
  'teamName' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'playerCount' : IDL.Nat,
  'durationMinutes' : IDL.Nat,
  'fieldId' : FieldId,
});
export const TeamId = IDL.Nat;
export const PlayerLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'good' : IDL.Null,
  'professional' : IDL.Null,
});
export const CreateMatchInput = IDL.Record({
  'awayTeamId' : TeamId,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'playerCount' : IDL.Nat,
  'homeTeamId' : TeamId,
  'level' : PlayerLevel,
  'pricePerPlayerDt' : IDL.Float64,
  'fieldId' : FieldId,
});
export const MatchId = IDL.Nat;
export const MatchStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const MatchView = IDL.Record({
  'id' : MatchId,
  'status' : MatchStatus,
  'awayTeamId' : TeamId,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'time' : IDL.Text,
  'playerCount' : IDL.Nat,
  'homeTeamId' : TeamId,
  'invitedPlayerIds' : IDL.Vec(UserId),
  'level' : PlayerLevel,
  'pricePerPlayerDt' : IDL.Float64,
  'fieldId' : FieldId,
});
export const CreateTeamInput = IDL.Record({
  'name' : IDL.Text,
  'color' : IDL.Text,
  'description' : IDL.Text,
  'level' : PlayerLevel,
  'logoUrl' : IDL.Opt(IDL.Text),
});
export const TeamView = IDL.Record({
  'id' : TeamId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'color' : IDL.Text,
  'playerCount' : IDL.Nat,
  'description' : IDL.Text,
  'level' : PlayerLevel,
  'logoUrl' : IDL.Opt(IDL.Text),
  'captain' : UserId,
  'memberIds' : IDL.Vec(UserId),
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'captain' : IDL.Null,
  'referee' : IDL.Null,
  'volunteer' : IDL.Null,
});
export const PlayerPosition = IDL.Variant({
  'goalkeeper' : IDL.Null,
  'winger' : IDL.Null,
  'midfielder' : IDL.Null,
  'defender' : IDL.Null,
  'striker' : IDL.Null,
});
export const AccountView = IDL.Record({
  'id' : UserId,
  'username' : IDL.Text,
  'city' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'banned' : IDL.Bool,
  'photoUrl' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'level' : PlayerLevel,
  'phone' : IDL.Text,
  'position' : PlayerPosition,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const AdminStats = IDL.Record({
  'totalTeams' : IDL.Nat,
  'totalMatches' : IDL.Nat,
  'totalPlayers' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'totalRevenueDt' : IDL.Float64,
  'totalUsers' : IDL.Nat,
});
export const RevenuePoint = IDL.Record({
  'monthLabel' : IDL.Text,
  'amountDt' : IDL.Float64,
});
export const AdminOverview = IDL.Record({
  'bookingsByStatus' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'stats' : AdminStats,
  'revenueByMonth' : IDL.Vec(RevenuePoint),
});
export const FieldView = IDL.Record({
  'id' : FieldId,
  'timeSlots' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'available' : IDL.Bool,
  'priceDt' : IDL.Float64,
  'imageUrl' : IDL.Opt(IDL.Text),
  'distanceKm' : IDL.Float64,
  'rating' : IDL.Float64,
  'location' : IDL.Text,
});
export const ShareCard = IDL.Record({
  'date' : IDL.Text,
  'shareUrl' : IDL.Text,
  'awayTeamName' : IDL.Text,
  'time' : IDL.Text,
  'homeTeamName' : IDL.Text,
  'fieldName' : IDL.Text,
  'location' : IDL.Text,
});
export const PlayerStats = IDL.Record({
  'assists' : IDL.Nat,
  'wins' : IDL.Nat,
  'goals' : IDL.Nat,
  'matchesPlayed' : IDL.Nat,
  'rating' : IDL.Float64,
});
export const PlayerProfile = IDL.Record({
  'teamIds' : IDL.Vec(IDL.Nat),
  'stats' : PlayerStats,
  'achievements' : IDL.Vec(IDL.Text),
  'account' : AccountView,
});
export const FieldFilter = IDL.Record({
  'minRating' : IDL.Opt(IDL.Float64),
  'maxPrice' : IDL.Opt(IDL.Float64),
  'maxDistanceKm' : IDL.Opt(IDL.Float64),
  'timeSlot' : IDL.Opt(IDL.Text),
});
export const AuthResult = IDL.Variant({ 'ok' : AccountView, 'err' : IDL.Text });
export const RegisterInput = IDL.Record({
  'username' : IDL.Text,
  'city' : IDL.Text,
  'password' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'level' : PlayerLevel,
  'phone' : IDL.Text,
  'position' : PlayerPosition,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const PlayerSearchFilter = IDL.Record({
  'minRating' : IDL.Opt(IDL.Float64),
  'availableToday' : IDL.Bool,
  'city' : IDL.Opt(IDL.Text),
  'level' : IDL.Opt(PlayerLevel),
  'position' : IDL.Opt(PlayerPosition),
  'availableAt' : IDL.Opt(IDL.Text),
});
export const AvailablePlayer = IDL.Record({
  'username' : IDL.Text,
  'city' : IDL.Text,
  'userId' : UserId,
  'level' : PlayerLevel,
  'available' : IDL.Bool,
  'rating' : IDL.Float64,
  'position' : PlayerPosition,
  'availableAt' : IDL.Opt(IDL.Text),
});
export const AvailabilityInput = IDL.Record({
  'available' : IDL.Bool,
  'availableAt' : IDL.Opt(IDL.Text),
});
export const UpdateProfileInput = IDL.Record({
  'username' : IDL.Text,
  'city' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'level' : PlayerLevel,
  'phone' : IDL.Text,
  'position' : PlayerPosition,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addTeamPlayer' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'confirmBookingPayment' : IDL.Func([IDL.Nat, IDL.Text], [PaymentResult], []),
  'createBooking' : IDL.Func([CreateBookingInput], [BookingView], []),
  'createMatch' : IDL.Func([CreateMatchInput], [MatchView], []),
  'createTeam' : IDL.Func([CreateTeamInput], [TeamView], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAccount' : IDL.Func([IDL.Principal], [IDL.Opt(AccountView)], ['query']),
  'getAdminOverview' : IDL.Func([], [AdminOverview], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(BookingView)], ['query']),
  'getCallerAccount' : IDL.Func([], [IDL.Opt(AccountView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getField' : IDL.Func([IDL.Nat], [IDL.Opt(FieldView)], ['query']),
  'getMatch' : IDL.Func([IDL.Nat], [IDL.Opt(MatchView)], ['query']),
  'getMatchShareCard' : IDL.Func([IDL.Nat], [IDL.Opt(ShareCard)], ['query']),
  'getPlayerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PlayerProfile)],
      ['query'],
    ),
  'getTeam' : IDL.Func([IDL.Nat], [IDL.Opt(TeamView)], ['query']),
  'inviteMatchPlayers' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Principal)],
      [IDL.Bool],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAccounts' : IDL.Func([], [IDL.Vec(AccountView)], ['query']),
  'listAllBookings' : IDL.Func([], [IDL.Vec(BookingView)], ['query']),
  'listFields' : IDL.Func([FieldFilter], [IDL.Vec(FieldView)], ['query']),
  'listMatches' : IDL.Func([], [IDL.Vec(MatchView)], ['query']),
  'listMyBookings' : IDL.Func([], [IDL.Vec(BookingView)], ['query']),
  'listTeams' : IDL.Func([], [IDL.Vec(TeamView)], ['query']),
  'login' : IDL.Func([IDL.Text], [AuthResult], []),
  'register' : IDL.Func([RegisterInput], [AuthResult], []),
  'removeTeamPlayer' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchPlayers' : IDL.Func(
      [PlayerSearchFilter],
      [IDL.Vec(AvailablePlayer)],
      ['query'],
    ),
  'setAccountBanned' : IDL.Func([IDL.Principal, IDL.Bool], [IDL.Bool], []),
  'setFieldAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'setMyAvailability' : IDL.Func([AvailabilityInput], [], []),
  'setTeamCaptain' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], []),
  'updateProfile' : IDL.Func([UpdateProfileInput], [AuthResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingId = IDL.Nat;
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const FieldId = IDL.Nat;
  const BookingView = IDL.Record({
    'id' : BookingId,
    'status' : BookingStatus,
    'teamName' : IDL.Text,
    'userId' : UserId,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'time' : IDL.Text,
    'playerCount' : IDL.Nat,
    'priceDt' : IDL.Float64,
    'durationMinutes' : IDL.Nat,
    'paymentReference' : IDL.Opt(IDL.Text),
    'fieldId' : FieldId,
  });
  const PaymentResult = IDL.Variant({ 'ok' : BookingView, 'err' : IDL.Text });
  const CreateBookingInput = IDL.Record({
    'teamName' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'playerCount' : IDL.Nat,
    'durationMinutes' : IDL.Nat,
    'fieldId' : FieldId,
  });
  const TeamId = IDL.Nat;
  const PlayerLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'good' : IDL.Null,
    'professional' : IDL.Null,
  });
  const CreateMatchInput = IDL.Record({
    'awayTeamId' : TeamId,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'playerCount' : IDL.Nat,
    'homeTeamId' : TeamId,
    'level' : PlayerLevel,
    'pricePerPlayerDt' : IDL.Float64,
    'fieldId' : FieldId,
  });
  const MatchId = IDL.Nat;
  const MatchStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const MatchView = IDL.Record({
    'id' : MatchId,
    'status' : MatchStatus,
    'awayTeamId' : TeamId,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'time' : IDL.Text,
    'playerCount' : IDL.Nat,
    'homeTeamId' : TeamId,
    'invitedPlayerIds' : IDL.Vec(UserId),
    'level' : PlayerLevel,
    'pricePerPlayerDt' : IDL.Float64,
    'fieldId' : FieldId,
  });
  const CreateTeamInput = IDL.Record({
    'name' : IDL.Text,
    'color' : IDL.Text,
    'description' : IDL.Text,
    'level' : PlayerLevel,
    'logoUrl' : IDL.Opt(IDL.Text),
  });
  const TeamView = IDL.Record({
    'id' : TeamId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'color' : IDL.Text,
    'playerCount' : IDL.Nat,
    'description' : IDL.Text,
    'level' : PlayerLevel,
    'logoUrl' : IDL.Opt(IDL.Text),
    'captain' : UserId,
    'memberIds' : IDL.Vec(UserId),
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'captain' : IDL.Null,
    'referee' : IDL.Null,
    'volunteer' : IDL.Null,
  });
  const PlayerPosition = IDL.Variant({
    'goalkeeper' : IDL.Null,
    'winger' : IDL.Null,
    'midfielder' : IDL.Null,
    'defender' : IDL.Null,
    'striker' : IDL.Null,
  });
  const AccountView = IDL.Record({
    'id' : UserId,
    'username' : IDL.Text,
    'city' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'banned' : IDL.Bool,
    'photoUrl' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'level' : PlayerLevel,
    'phone' : IDL.Text,
    'position' : PlayerPosition,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const AdminStats = IDL.Record({
    'totalTeams' : IDL.Nat,
    'totalMatches' : IDL.Nat,
    'totalPlayers' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'totalRevenueDt' : IDL.Float64,
    'totalUsers' : IDL.Nat,
  });
  const RevenuePoint = IDL.Record({
    'monthLabel' : IDL.Text,
    'amountDt' : IDL.Float64,
  });
  const AdminOverview = IDL.Record({
    'bookingsByStatus' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'stats' : AdminStats,
    'revenueByMonth' : IDL.Vec(RevenuePoint),
  });
  const FieldView = IDL.Record({
    'id' : FieldId,
    'timeSlots' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'available' : IDL.Bool,
    'priceDt' : IDL.Float64,
    'imageUrl' : IDL.Opt(IDL.Text),
    'distanceKm' : IDL.Float64,
    'rating' : IDL.Float64,
    'location' : IDL.Text,
  });
  const ShareCard = IDL.Record({
    'date' : IDL.Text,
    'shareUrl' : IDL.Text,
    'awayTeamName' : IDL.Text,
    'time' : IDL.Text,
    'homeTeamName' : IDL.Text,
    'fieldName' : IDL.Text,
    'location' : IDL.Text,
  });
  const PlayerStats = IDL.Record({
    'assists' : IDL.Nat,
    'wins' : IDL.Nat,
    'goals' : IDL.Nat,
    'matchesPlayed' : IDL.Nat,
    'rating' : IDL.Float64,
  });
  const PlayerProfile = IDL.Record({
    'teamIds' : IDL.Vec(IDL.Nat),
    'stats' : PlayerStats,
    'achievements' : IDL.Vec(IDL.Text),
    'account' : AccountView,
  });
  const FieldFilter = IDL.Record({
    'minRating' : IDL.Opt(IDL.Float64),
    'maxPrice' : IDL.Opt(IDL.Float64),
    'maxDistanceKm' : IDL.Opt(IDL.Float64),
    'timeSlot' : IDL.Opt(IDL.Text),
  });
  const AuthResult = IDL.Variant({ 'ok' : AccountView, 'err' : IDL.Text });
  const RegisterInput = IDL.Record({
    'username' : IDL.Text,
    'city' : IDL.Text,
    'password' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'level' : PlayerLevel,
    'phone' : IDL.Text,
    'position' : PlayerPosition,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const PlayerSearchFilter = IDL.Record({
    'minRating' : IDL.Opt(IDL.Float64),
    'availableToday' : IDL.Bool,
    'city' : IDL.Opt(IDL.Text),
    'level' : IDL.Opt(PlayerLevel),
    'position' : IDL.Opt(PlayerPosition),
    'availableAt' : IDL.Opt(IDL.Text),
  });
  const AvailablePlayer = IDL.Record({
    'username' : IDL.Text,
    'city' : IDL.Text,
    'userId' : UserId,
    'level' : PlayerLevel,
    'available' : IDL.Bool,
    'rating' : IDL.Float64,
    'position' : PlayerPosition,
    'availableAt' : IDL.Opt(IDL.Text),
  });
  const AvailabilityInput = IDL.Record({
    'available' : IDL.Bool,
    'availableAt' : IDL.Opt(IDL.Text),
  });
  const UpdateProfileInput = IDL.Record({
    'username' : IDL.Text,
    'city' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'level' : PlayerLevel,
    'phone' : IDL.Text,
    'position' : PlayerPosition,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addTeamPlayer' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'confirmBookingPayment' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [PaymentResult],
        [],
      ),
    'createBooking' : IDL.Func([CreateBookingInput], [BookingView], []),
    'createMatch' : IDL.Func([CreateMatchInput], [MatchView], []),
    'createTeam' : IDL.Func([CreateTeamInput], [TeamView], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAccount' : IDL.Func([IDL.Principal], [IDL.Opt(AccountView)], ['query']),
    'getAdminOverview' : IDL.Func([], [AdminOverview], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(BookingView)], ['query']),
    'getCallerAccount' : IDL.Func([], [IDL.Opt(AccountView)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getField' : IDL.Func([IDL.Nat], [IDL.Opt(FieldView)], ['query']),
    'getMatch' : IDL.Func([IDL.Nat], [IDL.Opt(MatchView)], ['query']),
    'getMatchShareCard' : IDL.Func([IDL.Nat], [IDL.Opt(ShareCard)], ['query']),
    'getPlayerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PlayerProfile)],
        ['query'],
      ),
    'getTeam' : IDL.Func([IDL.Nat], [IDL.Opt(TeamView)], ['query']),
    'inviteMatchPlayers' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Principal)],
        [IDL.Bool],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAccounts' : IDL.Func([], [IDL.Vec(AccountView)], ['query']),
    'listAllBookings' : IDL.Func([], [IDL.Vec(BookingView)], ['query']),
    'listFields' : IDL.Func([FieldFilter], [IDL.Vec(FieldView)], ['query']),
    'listMatches' : IDL.Func([], [IDL.Vec(MatchView)], ['query']),
    'listMyBookings' : IDL.Func([], [IDL.Vec(BookingView)], ['query']),
    'listTeams' : IDL.Func([], [IDL.Vec(TeamView)], ['query']),
    'login' : IDL.Func([IDL.Text], [AuthResult], []),
    'register' : IDL.Func([RegisterInput], [AuthResult], []),
    'removeTeamPlayer' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchPlayers' : IDL.Func(
        [PlayerSearchFilter],
        [IDL.Vec(AvailablePlayer)],
        ['query'],
      ),
    'setAccountBanned' : IDL.Func([IDL.Principal, IDL.Bool], [IDL.Bool], []),
    'setFieldAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'setMyAvailability' : IDL.Func([AvailabilityInput], [], []),
    'setTeamCaptain' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], []),
    'updateProfile' : IDL.Func([UpdateProfileInput], [AuthResult], []),
  });
};

export const init = ({ IDL }) => { return []; };