/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountView {
  'id' : UserId,
  'username' : string,
  'city' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'banned' : boolean,
  'photoUrl' : [] | [string],
  'email' : string,
  'level' : PlayerLevel,
  'phone' : string,
  'position' : PlayerPosition,
  'lastName' : string,
  'firstName' : string,
}
export interface AdminOverview {
  'bookingsByStatus' : Array<[string, bigint]>,
  'stats' : AdminStats,
  'revenueByMonth' : Array<RevenuePoint>,
}
export interface AdminStats {
  'totalTeams' : bigint,
  'totalMatches' : bigint,
  'totalPlayers' : bigint,
  'totalBookings' : bigint,
  'totalRevenueDt' : number,
  'totalUsers' : bigint,
}
export type AuthResult = { 'ok' : AccountView } |
  { 'err' : string };
export interface AvailabilityInput {
  'available' : boolean,
  'availableAt' : [] | [string],
}
export interface AvailablePlayer {
  'username' : string,
  'city' : string,
  'userId' : UserId,
  'level' : PlayerLevel,
  'available' : boolean,
  'rating' : number,
  'position' : PlayerPosition,
  'availableAt' : [] | [string],
}
export type BookingId = bigint;
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null };
export interface BookingView {
  'id' : BookingId,
  'status' : BookingStatus,
  'teamName' : string,
  'userId' : UserId,
  'date' : string,
  'createdAt' : Timestamp,
  'time' : string,
  'playerCount' : bigint,
  'priceDt' : number,
  'durationMinutes' : bigint,
  'paymentReference' : [] | [string],
  'fieldId' : FieldId,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface CreateBookingInput {
  'teamName' : string,
  'date' : string,
  'time' : string,
  'playerCount' : bigint,
  'durationMinutes' : bigint,
  'fieldId' : FieldId,
}
export interface CreateMatchInput {
  'awayTeamId' : TeamId,
  'date' : string,
  'time' : string,
  'playerCount' : bigint,
  'homeTeamId' : TeamId,
  'level' : PlayerLevel,
  'pricePerPlayerDt' : number,
  'fieldId' : FieldId,
}
export interface CreateTeamInput {
  'name' : string,
  'color' : string,
  'description' : string,
  'level' : PlayerLevel,
  'logoUrl' : [] | [string],
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface FieldFilter {
  'minRating' : [] | [number],
  'maxPrice' : [] | [number],
  'maxDistanceKm' : [] | [number],
  'timeSlot' : [] | [string],
}
export type FieldId = bigint;
export interface FieldView {
  'id' : FieldId,
  'timeSlots' : Array<string>,
  'name' : string,
  'available' : boolean,
  'priceDt' : number,
  'imageUrl' : [] | [string],
  'distanceKm' : number,
  'rating' : number,
  'location' : string,
}
export type MatchId = bigint;
export type MatchStatus = { 'scheduled' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export interface MatchView {
  'id' : MatchId,
  'status' : MatchStatus,
  'awayTeamId' : TeamId,
  'date' : string,
  'createdAt' : Timestamp,
  'time' : string,
  'playerCount' : bigint,
  'homeTeamId' : TeamId,
  'invitedPlayerIds' : Array<UserId>,
  'level' : PlayerLevel,
  'pricePerPlayerDt' : number,
  'fieldId' : FieldId,
}
export type PaymentResult = { 'ok' : BookingView } |
  { 'err' : string };
export type PlayerLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'good' : null } |
  { 'professional' : null };
export type PlayerPosition = { 'goalkeeper' : null } |
  { 'winger' : null } |
  { 'midfielder' : null } |
  { 'defender' : null } |
  { 'striker' : null };
export interface PlayerProfile {
  'teamIds' : Array<bigint>,
  'stats' : PlayerStats,
  'achievements' : Array<string>,
  'account' : AccountView,
}
export interface PlayerSearchFilter {
  'minRating' : [] | [number],
  'availableToday' : boolean,
  'city' : [] | [string],
  'level' : [] | [PlayerLevel],
  'position' : [] | [PlayerPosition],
  'availableAt' : [] | [string],
}
export interface PlayerStats {
  'assists' : bigint,
  'wins' : bigint,
  'goals' : bigint,
  'matchesPlayed' : bigint,
  'rating' : number,
}
export interface RegisterInput {
  'username' : string,
  'city' : string,
  'password' : string,
  'photoUrl' : [] | [string],
  'email' : string,
  'level' : PlayerLevel,
  'phone' : string,
  'position' : PlayerPosition,
  'lastName' : string,
  'firstName' : string,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface RevenuePoint { 'monthLabel' : string, 'amountDt' : number }
export interface ShareCard {
  'date' : string,
  'shareUrl' : string,
  'awayTeamName' : string,
  'time' : string,
  'homeTeamName' : string,
  'fieldName' : string,
  'location' : string,
}
export type TeamId = bigint;
export interface TeamView {
  'id' : TeamId,
  'name' : string,
  'createdAt' : Timestamp,
  'color' : string,
  'playerCount' : bigint,
  'description' : string,
  'level' : PlayerLevel,
  'logoUrl' : [] | [string],
  'captain' : UserId,
  'memberIds' : Array<UserId>,
}
export type Timestamp = bigint;
export interface UpdateProfileInput {
  'username' : string,
  'city' : string,
  'photoUrl' : [] | [string],
  'email' : string,
  'level' : PlayerLevel,
  'phone' : string,
  'position' : PlayerPosition,
  'lastName' : string,
  'firstName' : string,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'captain' : null } |
  { 'referee' : null } |
  { 'volunteer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addTeamPlayer' : ActorMethod<[bigint, Principal], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'cancelBooking' : ActorMethod<[bigint], boolean>,
  'confirmBookingPayment' : ActorMethod<[bigint, string], PaymentResult>,
  'createBooking' : ActorMethod<[CreateBookingInput], BookingView>,
  'createMatch' : ActorMethod<[CreateMatchInput], MatchView>,
  'createTeam' : ActorMethod<[CreateTeamInput], TeamView>,
  'execute' : ActorMethod<[string], Result>,
  'getAccount' : ActorMethod<[Principal], [] | [AccountView]>,
  'getAdminOverview' : ActorMethod<[], AdminOverview>,
  'getApiDoc' : ActorMethod<[], string>,
  'getBooking' : ActorMethod<[bigint], [] | [BookingView]>,
  'getCallerAccount' : ActorMethod<[], [] | [AccountView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getField' : ActorMethod<[bigint], [] | [FieldView]>,
  'getMatch' : ActorMethod<[bigint], [] | [MatchView]>,
  'getMatchShareCard' : ActorMethod<[bigint], [] | [ShareCard]>,
  'getPlayerProfile' : ActorMethod<[Principal], [] | [PlayerProfile]>,
  'getTeam' : ActorMethod<[bigint], [] | [TeamView]>,
  'inviteMatchPlayers' : ActorMethod<[bigint, Array<Principal>], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAccounts' : ActorMethod<[], Array<AccountView>>,
  'listAllBookings' : ActorMethod<[], Array<BookingView>>,
  'listFields' : ActorMethod<[FieldFilter], Array<FieldView>>,
  'listMatches' : ActorMethod<[], Array<MatchView>>,
  'listMyBookings' : ActorMethod<[], Array<BookingView>>,
  'listTeams' : ActorMethod<[], Array<TeamView>>,
  'login' : ActorMethod<[string], AuthResult>,
  'register' : ActorMethod<[RegisterInput], AuthResult>,
  'removeTeamPlayer' : ActorMethod<[bigint, Principal], boolean>,
  'schema' : ActorMethod<[], string>,
  'searchPlayers' : ActorMethod<[PlayerSearchFilter], Array<AvailablePlayer>>,
  'setAccountBanned' : ActorMethod<[Principal, boolean], boolean>,
  'setFieldAvailability' : ActorMethod<[bigint, boolean], boolean>,
  'setMyAvailability' : ActorMethod<[AvailabilityInput], undefined>,
  'setTeamCaptain' : ActorMethod<[bigint, Principal], boolean>,
  'updateProfile' : ActorMethod<[UpdateProfileInput], AuthResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];