/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface AccountView {
    id: UserId;
    username: string;
    city: string;
    createdAt: Timestamp;
    role: UserRole;
    banned: boolean;
    photoUrl?: string;
    email: string;
    level: PlayerLevel;
    phone: string;
    position: PlayerPosition;
    lastName: string;
    firstName: string;
}
export interface AdminOverview {
    bookingsByStatus: Array<[string, bigint]>;
    stats: AdminStats;
    revenueByMonth: Array<RevenuePoint>;
}
export interface AdminStats {
    totalTeams: bigint;
    totalMatches: bigint;
    totalPlayers: bigint;
    totalBookings: bigint;
    totalRevenueDt: number;
    totalUsers: bigint;
}
export type AuthResult = {
    __kind__: "ok";
    ok: AccountView;
} | {
    __kind__: "err";
    err: string;
};
export interface AvailabilityInput {
    available: boolean;
    availableAt?: string;
}
export interface AvailablePlayer {
    username: string;
    city: string;
    userId: UserId;
    level: PlayerLevel;
    available: boolean;
    rating: number;
    position: PlayerPosition;
    availableAt?: string;
}
export type BookingId = bigint;
export interface BookingView {
    id: BookingId;
    status: BookingStatus;
    teamName: string;
    userId: UserId;
    date: string;
    createdAt: Timestamp;
    time: string;
    playerCount: bigint;
    priceDt: number;
    durationMinutes: bigint;
    paymentReference?: string;
    fieldId: FieldId;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface CreateBookingInput {
    teamName: string;
    date: string;
    time: string;
    playerCount: bigint;
    durationMinutes: bigint;
    fieldId: FieldId;
}
export interface CreateMatchInput {
    awayTeamId: TeamId;
    date: string;
    time: string;
    playerCount: bigint;
    homeTeamId: TeamId;
    level: PlayerLevel;
    pricePerPlayerDt: number;
    fieldId: FieldId;
}
export interface CreateTeamInput {
    name: string;
    color: string;
    description: string;
    level: PlayerLevel;
    logoUrl?: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface FieldFilter {
    minRating?: number;
    maxPrice?: number;
    maxDistanceKm?: number;
    timeSlot?: string;
}
export type FieldId = bigint;
export interface FieldView {
    id: FieldId;
    timeSlots: Array<string>;
    name: string;
    available: boolean;
    priceDt: number;
    imageUrl?: string;
    distanceKm: number;
    rating: number;
    location: string;
}
export type MatchId = bigint;
export interface MatchView {
    id: MatchId;
    status: MatchStatus;
    awayTeamId: TeamId;
    date: string;
    createdAt: Timestamp;
    time: string;
    playerCount: bigint;
    homeTeamId: TeamId;
    invitedPlayerIds: Array<UserId>;
    level: PlayerLevel;
    pricePerPlayerDt: number;
    fieldId: FieldId;
}
export type PaymentResult = {
    __kind__: "ok";
    ok: BookingView;
} | {
    __kind__: "err";
    err: string;
};
export interface PlayerProfile {
    teamIds: Array<bigint>;
    stats: PlayerStats;
    achievements: Array<string>;
    account: AccountView;
}
export interface PlayerSearchFilter {
    minRating?: number;
    availableToday: boolean;
    city?: string;
    level?: PlayerLevel;
    position?: PlayerPosition;
    availableAt?: string;
}
export interface PlayerStats {
    assists: bigint;
    wins: bigint;
    goals: bigint;
    matchesPlayed: bigint;
    rating: number;
}
export interface RegisterInput {
    username: string;
    city: string;
    password: string;
    photoUrl?: string;
    email: string;
    level: PlayerLevel;
    phone: string;
    position: PlayerPosition;
    lastName: string;
    firstName: string;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface RevenuePoint {
    monthLabel: string;
    amountDt: number;
}
export interface ShareCard {
    date: string;
    shareUrl: string;
    awayTeamName: string;
    time: string;
    homeTeamName: string;
    fieldName: string;
    location: string;
}
export type TeamId = bigint;
export interface TeamView {
    id: TeamId;
    name: string;
    createdAt: Timestamp;
    color: string;
    playerCount: bigint;
    description: string;
    level: PlayerLevel;
    logoUrl?: string;
    captain: UserId;
    memberIds: Array<UserId>;
}
export type Timestamp = bigint;
export interface UpdateProfileInput {
    username: string;
    city: string;
    photoUrl?: string;
    email: string;
    level: PlayerLevel;
    phone: string;
    position: PlayerPosition;
    lastName: string;
    firstName: string;
}
export type UserId = Principal;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    paid = "paid"
}
export enum MatchStatus {
    scheduled = "scheduled",
    cancelled = "cancelled",
    completed = "completed"
}
export enum PlayerLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    good = "good",
    professional = "professional"
}
export enum PlayerPosition {
    goalkeeper = "goalkeeper",
    winger = "winger",
    midfielder = "midfielder",
    defender = "defender",
    striker = "striker"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    captain = "captain",
    referee = "referee",
    volunteer = "volunteer"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addTeamPlayer(teamId: bigint, player: Principal): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    cancelBooking(bookingId: bigint): Promise<boolean>;
    confirmBookingPayment(bookingId: bigint, paymentReference: string): Promise<PaymentResult>;
    createBooking(input: CreateBookingInput): Promise<BookingView>;
    createMatch(input: CreateMatchInput): Promise<MatchView>;
    createTeam(input: CreateTeamInput): Promise<TeamView>;
    execute(qJson: string): Promise<Result>;
    getAccount(user: Principal): Promise<AccountView | null>;
    getAdminOverview(): Promise<AdminOverview>;
    getApiDoc(): Promise<string>;
    getBooking(bookingId: bigint): Promise<BookingView | null>;
    getCallerAccount(): Promise<AccountView | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getField(id: bigint): Promise<FieldView | null>;
    getMatch(matchId: bigint): Promise<MatchView | null>;
    getMatchShareCard(matchId: bigint): Promise<ShareCard | null>;
    getPlayerProfile(user: Principal): Promise<PlayerProfile | null>;
    getTeam(teamId: bigint): Promise<TeamView | null>;
    inviteMatchPlayers(matchId: bigint, players: Array<Principal>): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listAccounts(): Promise<Array<AccountView>>;
    listAllBookings(): Promise<Array<BookingView>>;
    listFields(filter: FieldFilter): Promise<Array<FieldView>>;
    listMatches(): Promise<Array<MatchView>>;
    listMyBookings(): Promise<Array<BookingView>>;
    listTeams(): Promise<Array<TeamView>>;
    login(password: string): Promise<AuthResult>;
    register(input: RegisterInput): Promise<AuthResult>;
    removeTeamPlayer(teamId: bigint, player: Principal): Promise<boolean>;
    schema(): Promise<string>;
    searchPlayers(filter: PlayerSearchFilter): Promise<Array<AvailablePlayer>>;
    setAccountBanned(user: Principal, banned: boolean): Promise<boolean>;
    setFieldAvailability(id: bigint, available: boolean): Promise<boolean>;
    setMyAvailability(input: AvailabilityInput): Promise<void>;
    setTeamCaptain(teamId: bigint, newCaptain: Principal): Promise<boolean>;
    updateProfile(input: UpdateProfileInput): Promise<AuthResult>;
}
import type { AccountView as _AccountView, AuthResult as _AuthResult, AvailabilityInput as _AvailabilityInput, AvailablePlayer as _AvailablePlayer, BookingId as _BookingId, BookingStatus as _BookingStatus, BookingView as _BookingView, Cell as _Cell, CreateMatchInput as _CreateMatchInput, CreateTeamInput as _CreateTeamInput, Error as _Error, FieldFilter as _FieldFilter, FieldId as _FieldId, FieldView as _FieldView, MatchId as _MatchId, MatchStatus as _MatchStatus, MatchView as _MatchView, PaymentResult as _PaymentResult, PlayerLevel as _PlayerLevel, PlayerPosition as _PlayerPosition, PlayerProfile as _PlayerProfile, PlayerSearchFilter as _PlayerSearchFilter, PlayerStats as _PlayerStats, RegisterInput as _RegisterInput, Result as _Result, Result__1 as _Result__1, ShareCard as _ShareCard, TeamId as _TeamId, TeamView as _TeamView, Timestamp as _Timestamp, UpdateProfileInput as _UpdateProfileInput, UserId as _UserId, UserRole as _UserRole, UserRole__1 as _UserRole__1, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addTeamPlayer(arg0: bigint, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeamPlayer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeamPlayer(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelBooking(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async confirmBookingPayment(arg0: bigint, arg1: string): Promise<PaymentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmBookingPayment(arg0, arg1);
                return from_candid_PaymentResult_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmBookingPayment(arg0, arg1);
            return from_candid_PaymentResult_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBooking(arg0: CreateBookingInput): Promise<BookingView> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0);
                return from_candid_BookingView_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0);
            return from_candid_BookingView_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async createMatch(arg0: CreateMatchInput): Promise<MatchView> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(to_candid_CreateMatchInput_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_MatchView_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(to_candid_CreateMatchInput_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_MatchView_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTeam(arg0: CreateTeamInput): Promise<TeamView> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeam(to_candid_CreateTeamInput_n19(this._uploadFile, this._downloadFile, arg0));
                return from_candid_TeamView_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeam(to_candid_CreateTeamInput_n19(this._uploadFile, this._downloadFile, arg0));
            return from_candid_TeamView_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAccount(arg0: Principal): Promise<AccountView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccount(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccount(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminOverview(): Promise<AdminOverview> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminOverview();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminOverview();
            return result;
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getBooking(arg0: bigint): Promise<BookingView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerAccount(): Promise<AccountView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerAccount();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerAccount();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getField(arg0: bigint): Promise<FieldView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getField(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getField(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatch(arg0: bigint): Promise<MatchView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchShareCard(arg0: bigint): Promise<ShareCard | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchShareCard(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchShareCard(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerProfile(arg0: Principal): Promise<PlayerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerProfile(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerProfile(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeam(arg0: bigint): Promise<TeamView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeam(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeam(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async inviteMatchPlayers(arg0: bigint, arg1: Array<Principal>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.inviteMatchPlayers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inviteMatchPlayers(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAccounts(): Promise<Array<AccountView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAccounts();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAccounts();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllBookings(): Promise<Array<BookingView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllBookings();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllBookings();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFields(arg0: FieldFilter): Promise<Array<FieldView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFields(to_candid_FieldFilter_n49(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFields(to_candid_FieldFilter_n49(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMatches(): Promise<Array<MatchView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMatches();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMatches();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyBookings(): Promise<Array<BookingView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyBookings();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyBookings();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTeams(): Promise<Array<TeamView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTeams();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTeams();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0);
                return from_candid_AuthResult_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0);
            return from_candid_AuthResult_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(arg0: RegisterInput): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.register(to_candid_RegisterInput_n56(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AuthResult_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(to_candid_RegisterInput_n56(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AuthResult_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeTeamPlayer(arg0: bigint, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTeamPlayer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTeamPlayer(arg0, arg1);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async searchPlayers(arg0: PlayerSearchFilter): Promise<Array<AvailablePlayer>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPlayers(to_candid_PlayerSearchFilter_n59(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPlayers(to_candid_PlayerSearchFilter_n59(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAccountBanned(arg0: Principal, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setAccountBanned(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAccountBanned(arg0, arg1);
            return result;
        }
    }
    async setFieldAvailability(arg0: bigint, arg1: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setFieldAvailability(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFieldAvailability(arg0, arg1);
            return result;
        }
    }
    async setMyAvailability(arg0: AvailabilityInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMyAvailability(to_candid_AvailabilityInput_n64(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMyAvailability(to_candid_AvailabilityInput_n64(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setTeamCaptain(arg0: bigint, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setTeamCaptain(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTeamCaptain(arg0, arg1);
            return result;
        }
    }
    async updateProfile(arg0: UpdateProfileInput): Promise<AuthResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(to_candid_UpdateProfileInput_n66(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AuthResult_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(to_candid_UpdateProfileInput_n66(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AuthResult_n54(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AccountView_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountView): AccountView {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_AuthResult_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthResult): AuthResult {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_AvailablePlayer_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvailablePlayer): AvailablePlayer {
    return from_candid_record_n63(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "paid" in value ? BookingStatus.paid : value;
}
function from_candid_BookingView_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingView): BookingView {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_FieldView_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FieldView): FieldView {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return "scheduled" in value ? MatchStatus.scheduled : "cancelled" in value ? MatchStatus.cancelled : "completed" in value ? MatchStatus.completed : value;
}
function from_candid_MatchView_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchView): MatchView {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentResult_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentResult): PaymentResult {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerLevel_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerLevel): PlayerLevel {
    return "intermediate" in value ? PlayerLevel.intermediate : "beginner" in value ? PlayerLevel.beginner : "good" in value ? PlayerLevel.good : "professional" in value ? PlayerLevel.professional : value;
}
function from_candid_PlayerPosition_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerPosition): PlayerPosition {
    return "goalkeeper" in value ? PlayerPosition.goalkeeper : "winger" in value ? PlayerPosition.winger : "midfielder" in value ? PlayerPosition.midfielder : "defender" in value ? PlayerPosition.defender : "striker" in value ? PlayerPosition.striker : value;
}
function from_candid_PlayerProfile_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerProfile): PlayerProfile {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_TeamView_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TeamView): TeamView {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "captain" in value ? UserRole.captain : "referee" in value ? UserRole.referee : "volunteer" in value ? UserRole.volunteer : value;
}
function from_candid_Value_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AccountView]): AccountView | null {
    return value.length === 0 ? null : from_candid_AccountView_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BookingView]): BookingView | null {
    return value.length === 0 ? null : from_candid_BookingView_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FieldView]): FieldView | null {
    return value.length === 0 ? null : from_candid_FieldView_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MatchView]): MatchView | null {
    return value.length === 0 ? null : from_candid_MatchView_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ShareCard]): ShareCard | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerProfile]): PlayerProfile | null {
    return value.length === 0 ? null : from_candid_PlayerProfile_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeamView]): TeamView | null {
    return value.length === 0 ? null : from_candid_TeamView_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MatchId;
    status: _MatchStatus;
    awayTeamId: _TeamId;
    date: string;
    createdAt: _Timestamp;
    time: string;
    playerCount: bigint;
    homeTeamId: _TeamId;
    invitedPlayerIds: Array<_UserId>;
    level: _PlayerLevel;
    pricePerPlayerDt: number;
    fieldId: _FieldId;
}): {
    id: MatchId;
    status: MatchStatus;
    awayTeamId: TeamId;
    date: string;
    createdAt: Timestamp;
    time: string;
    playerCount: bigint;
    homeTeamId: TeamId;
    invitedPlayerIds: Array<UserId>;
    level: PlayerLevel;
    pricePerPlayerDt: number;
    fieldId: FieldId;
} {
    return {
        id: value.id,
        status: from_candid_MatchStatus_n17(_uploadFile, _downloadFile, value.status),
        awayTeamId: value.awayTeamId,
        date: value.date,
        createdAt: value.createdAt,
        time: value.time,
        playerCount: value.playerCount,
        homeTeamId: value.homeTeamId,
        invitedPlayerIds: value.invitedPlayerIds,
        level: from_candid_PlayerLevel_n18(_uploadFile, _downloadFile, value.level),
        pricePerPlayerDt: value.pricePerPlayerDt,
        fieldId: value.fieldId
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TeamId;
    name: string;
    createdAt: _Timestamp;
    color: string;
    playerCount: bigint;
    description: string;
    level: _PlayerLevel;
    logoUrl: [] | [string];
    captain: _UserId;
    memberIds: Array<_UserId>;
}): {
    id: TeamId;
    name: string;
    createdAt: Timestamp;
    color: string;
    playerCount: bigint;
    description: string;
    level: PlayerLevel;
    logoUrl?: string;
    captain: UserId;
    memberIds: Array<UserId>;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        color: value.color,
        playerCount: value.playerCount,
        description: value.description,
        level: from_candid_PlayerLevel_n18(_uploadFile, _downloadFile, value.level),
        logoUrl: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.logoUrl)),
        captain: value.captain,
        memberIds: value.memberIds
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n25(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n29(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    username: string;
    city: string;
    createdAt: _Timestamp;
    role: _UserRole;
    banned: boolean;
    photoUrl: [] | [string];
    email: string;
    level: _PlayerLevel;
    phone: string;
    position: _PlayerPosition;
    lastName: string;
    firstName: string;
}): {
    id: UserId;
    username: string;
    city: string;
    createdAt: Timestamp;
    role: UserRole;
    banned: boolean;
    photoUrl?: string;
    email: string;
    level: PlayerLevel;
    phone: string;
    position: PlayerPosition;
    lastName: string;
    firstName: string;
} {
    return {
        id: value.id,
        username: value.username,
        city: value.city,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n34(_uploadFile, _downloadFile, value.role),
        banned: value.banned,
        photoUrl: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.photoUrl)),
        email: value.email,
        level: from_candid_PlayerLevel_n18(_uploadFile, _downloadFile, value.level),
        phone: value.phone,
        position: from_candid_PlayerPosition_n35(_uploadFile, _downloadFile, value.position),
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FieldId;
    timeSlots: Array<string>;
    name: string;
    available: boolean;
    priceDt: number;
    imageUrl: [] | [string];
    distanceKm: number;
    rating: number;
    location: string;
}): {
    id: FieldId;
    timeSlots: Array<string>;
    name: string;
    available: boolean;
    priceDt: number;
    imageUrl?: string;
    distanceKm: number;
    rating: number;
    location: string;
} {
    return {
        id: value.id,
        timeSlots: value.timeSlots,
        name: value.name,
        available: value.available,
        priceDt: value.priceDt,
        imageUrl: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.imageUrl)),
        distanceKm: value.distanceKm,
        rating: value.rating,
        location: value.location
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    teamIds: Array<bigint>;
    stats: _PlayerStats;
    achievements: Array<string>;
    account: _AccountView;
}): {
    teamIds: Array<bigint>;
    stats: PlayerStats;
    achievements: Array<string>;
    account: AccountView;
} {
    return {
        teamIds: value.teamIds,
        stats: value.stats,
        achievements: value.achievements,
        account: from_candid_AccountView_n32(_uploadFile, _downloadFile, value.account)
    };
}
function from_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    city: string;
    userId: _UserId;
    level: _PlayerLevel;
    available: boolean;
    rating: number;
    position: _PlayerPosition;
    availableAt: [] | [string];
}): {
    username: string;
    city: string;
    userId: UserId;
    level: PlayerLevel;
    available: boolean;
    rating: number;
    position: PlayerPosition;
    availableAt?: string;
} {
    return {
        username: value.username,
        city: value.city,
        userId: value.userId,
        level: from_candid_PlayerLevel_n18(_uploadFile, _downloadFile, value.level),
        available: value.available,
        rating: value.rating,
        position: from_candid_PlayerPosition_n35(_uploadFile, _downloadFile, value.position),
        availableAt: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.availableAt))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BookingId;
    status: _BookingStatus;
    teamName: string;
    userId: _UserId;
    date: string;
    createdAt: _Timestamp;
    time: string;
    playerCount: bigint;
    priceDt: number;
    durationMinutes: bigint;
    paymentReference: [] | [string];
    fieldId: _FieldId;
}): {
    id: BookingId;
    status: BookingStatus;
    teamName: string;
    userId: UserId;
    date: string;
    createdAt: Timestamp;
    time: string;
    playerCount: bigint;
    priceDt: number;
    durationMinutes: bigint;
    paymentReference?: string;
    fieldId: FieldId;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n10(_uploadFile, _downloadFile, value.status),
        teamName: value.teamName,
        userId: value.userId,
        date: value.date,
        createdAt: value.createdAt,
        time: value.time,
        playerCount: value.playerCount,
        priceDt: value.priceDt,
        durationMinutes: value.durationMinutes,
        paymentReference: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.paymentReference)),
        fieldId: value.fieldId
    };
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AccountView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AccountView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_AccountView_n32(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _BookingView;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: BookingView;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_BookingView_n8(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AccountView>): Array<AccountView> {
    return value.map((x)=>from_candid_AccountView_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingView>): Array<BookingView> {
    return value.map((x)=>from_candid_BookingView_n8(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FieldView>): Array<FieldView> {
    return value.map((x)=>from_candid_FieldView_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MatchView>): Array<MatchView> {
    return value.map((x)=>from_candid_MatchView_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TeamView>): Array<TeamView> {
    return value.map((x)=>from_candid_TeamView_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AvailablePlayer>): Array<AvailablePlayer> {
    return value.map((x)=>from_candid_AvailablePlayer_n62(_uploadFile, _downloadFile, x));
}
function to_candid_AvailabilityInput_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvailabilityInput): _AvailabilityInput {
    return to_candid_record_n65(_uploadFile, _downloadFile, value);
}
function to_candid_CreateMatchInput_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateMatchInput): _CreateMatchInput {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_CreateTeamInput_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateTeamInput): _CreateTeamInput {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_FieldFilter_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FieldFilter): _FieldFilter {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_PlayerLevel_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerLevel): _PlayerLevel {
    return value == PlayerLevel.intermediate ? {
        intermediate: null
    } : value == PlayerLevel.beginner ? {
        beginner: null
    } : value == PlayerLevel.good ? {
        good: null
    } : value == PlayerLevel.professional ? {
        professional: null
    } : value;
}
function to_candid_PlayerPosition_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerPosition): _PlayerPosition {
    return value == PlayerPosition.goalkeeper ? {
        goalkeeper: null
    } : value == PlayerPosition.winger ? {
        winger: null
    } : value == PlayerPosition.midfielder ? {
        midfielder: null
    } : value == PlayerPosition.defender ? {
        defender: null
    } : value == PlayerPosition.striker ? {
        striker: null
    } : value;
}
function to_candid_PlayerSearchFilter_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlayerSearchFilter): _PlayerSearchFilter {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_RegisterInput_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterInput): _RegisterInput {
    return to_candid_record_n57(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProfileInput_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProfileInput): _UpdateProfileInput {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    awayTeamId: TeamId;
    date: string;
    time: string;
    playerCount: bigint;
    homeTeamId: TeamId;
    level: PlayerLevel;
    pricePerPlayerDt: number;
    fieldId: FieldId;
}): {
    awayTeamId: _TeamId;
    date: string;
    time: string;
    playerCount: bigint;
    homeTeamId: _TeamId;
    level: _PlayerLevel;
    pricePerPlayerDt: number;
    fieldId: _FieldId;
} {
    return {
        awayTeamId: value.awayTeamId,
        date: value.date,
        time: value.time,
        playerCount: value.playerCount,
        homeTeamId: value.homeTeamId,
        level: to_candid_PlayerLevel_n14(_uploadFile, _downloadFile, value.level),
        pricePerPlayerDt: value.pricePerPlayerDt,
        fieldId: value.fieldId
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    color: string;
    description: string;
    level: PlayerLevel;
    logoUrl?: string;
}): {
    name: string;
    color: string;
    description: string;
    level: _PlayerLevel;
    logoUrl: [] | [string];
} {
    return {
        name: value.name,
        color: value.color,
        description: value.description,
        level: to_candid_PlayerLevel_n14(_uploadFile, _downloadFile, value.level),
        logoUrl: value.logoUrl ? candid_some(value.logoUrl) : candid_none()
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minRating?: number;
    maxPrice?: number;
    maxDistanceKm?: number;
    timeSlot?: string;
}): {
    minRating: [] | [number];
    maxPrice: [] | [number];
    maxDistanceKm: [] | [number];
    timeSlot: [] | [string];
} {
    return {
        minRating: value.minRating ? candid_some(value.minRating) : candid_none(),
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        maxDistanceKm: value.maxDistanceKm ? candid_some(value.maxDistanceKm) : candid_none(),
        timeSlot: value.timeSlot ? candid_some(value.timeSlot) : candid_none()
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    city: string;
    password: string;
    photoUrl?: string;
    email: string;
    level: PlayerLevel;
    phone: string;
    position: PlayerPosition;
    lastName: string;
    firstName: string;
}): {
    username: string;
    city: string;
    password: string;
    photoUrl: [] | [string];
    email: string;
    level: _PlayerLevel;
    phone: string;
    position: _PlayerPosition;
    lastName: string;
    firstName: string;
} {
    return {
        username: value.username,
        city: value.city,
        password: value.password,
        photoUrl: value.photoUrl ? candid_some(value.photoUrl) : candid_none(),
        email: value.email,
        level: to_candid_PlayerLevel_n14(_uploadFile, _downloadFile, value.level),
        phone: value.phone,
        position: to_candid_PlayerPosition_n58(_uploadFile, _downloadFile, value.position),
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minRating?: number;
    availableToday: boolean;
    city?: string;
    level?: PlayerLevel;
    position?: PlayerPosition;
    availableAt?: string;
}): {
    minRating: [] | [number];
    availableToday: boolean;
    city: [] | [string];
    level: [] | [_PlayerLevel];
    position: [] | [_PlayerPosition];
    availableAt: [] | [string];
} {
    return {
        minRating: value.minRating ? candid_some(value.minRating) : candid_none(),
        availableToday: value.availableToday,
        city: value.city ? candid_some(value.city) : candid_none(),
        level: value.level ? candid_some(to_candid_PlayerLevel_n14(_uploadFile, _downloadFile, value.level)) : candid_none(),
        position: value.position ? candid_some(to_candid_PlayerPosition_n58(_uploadFile, _downloadFile, value.position)) : candid_none(),
        availableAt: value.availableAt ? candid_some(value.availableAt) : candid_none()
    };
}
function to_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    available: boolean;
    availableAt?: string;
}): {
    available: boolean;
    availableAt: [] | [string];
} {
    return {
        available: value.available,
        availableAt: value.availableAt ? candid_some(value.availableAt) : candid_none()
    };
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    city: string;
    photoUrl?: string;
    email: string;
    level: PlayerLevel;
    phone: string;
    position: PlayerPosition;
    lastName: string;
    firstName: string;
}): {
    username: string;
    city: string;
    photoUrl: [] | [string];
    email: string;
    level: _PlayerLevel;
    phone: string;
    position: _PlayerPosition;
    lastName: string;
    firstName: string;
} {
    return {
        username: value.username,
        city: value.city,
        photoUrl: value.photoUrl ? candid_some(value.photoUrl) : candid_none(),
        email: value.email,
        level: to_candid_PlayerLevel_n14(_uploadFile, _downloadFile, value.level),
        phone: value.phone,
        position: to_candid_PlayerPosition_n58(_uploadFile, _downloadFile, value.position),
        lastName: value.lastName,
        firstName: value.firstName
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
